### ISSUE TITLE
[BUG] Navbar is not fixed on top 

### ISSUE THREAD

**Issue by aryadevesh** [MitulSonagara/truth-tunnel#100]
**Describe the bug**
The bug is that the navbar is not fixed on top for better user experience.
**To Reproduce**
1. Go to Home page
3. Scroll down
4. See the navbar is not visible 

**Expected behavior**
The navbar should be fixed on top.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/db2a31a7-8772-4fa5-9341-ecd48512f4a7">

**Desktop (please complete the following information):**
- In every device it would happen.

**Smartphone (please complete the following information):**
- In every device it would happen.

**Additional context**
Every website in which I raised this issue they considered so please you might also consider to assign me. Thank you

**Comment by MitulSonagara** [comment]
@aryadevesh go for it
