### ISSUE TITLE
[BUG]Handle debounce on edit user name (loader)

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#102]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

I am making it level 3 ... so also add username is available or not like in sign up page
