### ISSUE TITLE
Validation Errors Not Displaying on Sign In Form

### ISSUE THREAD

**Issue by mohit-2003** [MitulSonagara/truth-tunnel#12]
When users submit the form with blank fields, no error message is displayed to prompt the user to fill in the required fields, leading to poor user experience.

**Comment by mohit-2003** [comment]
I would like to contribute by fixing this issue as part of my GSSoC Extd and Hacktoberfest participation. Kindly let me know the process for making this contribution.

**Comment by MitulSonagara** [comment]
@mohit-2003 

Its already showing toast error message but you can try for highlighting the input fields and show error message there

**Comment by mohit-2003** [comment]
Okay, I will do that.
Please assign it to me and add labels for gssoc-extd, hacktoberfest and levels.

**Comment by MitulSonagara** [comment]
@mohit-2003 

Are you working on this issue?

**Comment by Sourabh782** [comment]
> @mohit-2003
> 
> Are you working on this issue?

hii is this issue free? if yes i m intrested

**Comment by MitulSonagara** [comment]
@Sourabh782 

you can work on this... i am assigning this to you...

**Comment by Sourabh782** [comment]
thanks @MitulSonagara , i'll be raising a pr till tommorow
