### ISSUE TITLE
[BUG] Navbar is not responsive in mobile-view

### ISSUE THREAD

**Issue by aryadevesh** [MitulSonagara/truth-tunnel#121]
**Describe the bug**
The responsiveness is not there for mobile phone screen.

**To Reproduce**
1. Go to Home page in mobile phone view of iphone SE size in inspect section. 

**Expected behavior**
It should be converted into hamburger button to show all the navbar items.
**Screenshots**

<img width="531" alt="image" src="https://github.com/user-attachments/assets/8abc3f67-6b5d-4770-9e4e-2898042b1ff5">

**Smartphone (please complete the following information):**
 - Device: [iPhone SE]
 - Browser [Chrome]

**Additional context**

**Comment by MitulSonagara** [comment]
@aryadevesh 

you can start working
