### ISSUE TITLE
[BUG] Code quality improvement remove staled code

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#122]
**Describe the bug**
Some points that can improve overall project

1. remove all staled code and functions
2. remove duplicate code make it simple
3. add `react-query` instead of traditional `useEffect`
4. revamp API routes with best practices.

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

You can start working...

and make sure you will not affect the overall performance of the code
