### ISSUE TITLE
[BUG] The Home page mid content div is not responsive. 

### ISSUE THREAD

**Issue by aryadevesh** [MitulSonagara/truth-tunnel#124]
**Describe the bug**
When I open the home page in iphone xr or same size phones the responsiveness of the UI breaks. 

**To Reproduce**
1. Go to Home page
3. Scroll down a little.

**Expected behavior**
The div should be accordingly adjusted with the size of the screen.

**Screenshots**
<img width="561" alt="image" src="https://github.com/user-attachments/assets/5bbb5847-8548-4a98-94a5-d8997d6ecee2">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone XR]

**Additional context**

**Comment by MitulSonagara** [comment]
@aryadevesh 

Go for it

**Comment by aryadevesh** [comment]
Will raise pr today.
