### ISSUE TITLE
[BUG] Not able to scroll down in Encryption pop-up window

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#125]
**Describe the bug**
Not able to scroll down in Encryption pop-up window

**To Reproduce**
1. Go to Encryption 
2. Click on Encryption 

**Expected behavior**

**Screenshots**
![o2](https://github.com/user-attachments/assets/67c3eb68-dd73-4f50-87bc-becf3d51fec0)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

Go for it
