### ISSUE TITLE
[FEATURE] Implement a profile option in the nav bar to access user info

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#126]
**Is your feature request related to a problem? Please describe.**
Implement a user profile option in the navigation bar to allow easy access to personal information

**Describe the solution you'd like**
![o4](https://github.com/user-attachments/assets/db69512d-3ccd-4084-87ae-fdc0eb545b19)
**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

You can start working, i am assigning this to you
