### ISSUE TITLE
[FEATURE] add faq section popup modal

### ISSUE THREAD

**Issue by ananyag309** [MitulSonagara/truth-tunnel#128]
design faq section popup modal at footer

To design a FAQ section popup modal at the footer, implement a "FAQ" button that opens a modal overlay when clicked. The modal should display frequently asked questions in a clean, scrollable interface with a close button. Place this at the footer for easy access without disrupting the page layout.

**Comment by MitulSonagara** [comment]
@ananyag309 
go for it

**Comment by MitulSonagara** [comment]
@ananyag309 

Are you working on this???
