### ISSUE TITLE
Addfeedback option

### ISSUE THREAD

**Issue by Aditijainnn** [MitulSonagara/truth-tunnel#129]
![image](https://github.com/user-attachments/assets/ed3d2e10-7548-4a16-8794-c5353a75888d)
add feedback option for better user interaction

**Comment by MitulSonagara** [comment]
@Aditijainnn You can start working

**Comment by meghanakn473** [comment]
@MitulSonagara please assign this issue to me i want to work on it

**Comment by Aditijainnn** [comment]
> @Aditijainnn You can start working

okk

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
can you allot me i will submit pr by night

**Comment by meghanakn473** [comment]
Hey @MitulSonagara as @Aditijainnn has not responded to he issue can u please assign me the issue?

**Comment by MitulSonagara** [comment]
@KapuluruBhuvaneswariVspdbct 

I am assigning this to you

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
thank you sir
