### ISSUE TITLE
Issue: User Model Problems

### ISSUE THREAD

**Issue by BaibhavTiwari** [MitulSonagara/truth-tunnel#13]
I've noticed a few issues with the current implementation of the `User` model in Mongoose that need to be addressed. Here's a breakdown of the problems I've identified:

### 1. **Inconsistent Error Message Style**
- The error messages for `username`, `email`, `password`, `verifyCode`, and `verifyCodeExpiry` fields are inconsistent in terms of tone and structure.
  - Example: `"Email is required"` vs `"Please use a valid email"`

### 2. **Indexing for Unique Fields**
- `username` and `email` are marked as `unique`, but Mongoose does not create an actual index unless it's explicitly defined. This could lead to issues with enforcing uniqueness at the database level.

### 3. **Handling `verifyCode` and `verifyCodeExpiry`**
- There is no logic in place for validating the verification code's expiration or handling invalid/expired verification codes.

### 4. **Default for `createdAt` in `MessageSchema`**
- The current `createdAt` field uses `default: Date.now`, which executes when the model is compiled rather than when the document is created. This could lead to incorrect timestamps.

### 5. **Subdocument vs Reference for `messages` Field**
- The `messages` array in the `UserSchema` uses the `Message` schema directly, creating subdocuments instead of references to separate `Message` documents.

### 6. **Security Concern: Plain-Text Password Storage**
- Passwords are currently stored in plain text, which is a security risk. The password should be hashed before being saved to the database.

### 7. **Message Type in `User` Interface**
- The `messages` field in the `User` interface is typed as `Message[]`. If messages are stored as references (ObjectIds), this type should be updated to reflect that.

**Comment by MitulSonagara** [comment]
@BaibhavTiwari go for it
