### ISSUE TITLE
Bug Fixes and Enhancements for Sign-Up Functionality in Page.tsx

### ISSUE THREAD

**Issue by chikatlarakesh** [MitulSonagara/truth-tunnel#14]
### Issue Description:
I encountered several bugs and potential enhancements in the `Page.tsx` file related to the sign-up functionality:

1. **Missing Validation Messages**: The validation messages for the email and password fields are not currently displayed. Users should receive feedback if their input doesn't meet the requirements.

2. **Username Availability Message**: The username availability message is not resetting properly when the user starts typing a new username. This could lead to confusion regarding whether the new username is available.

3. **Styling Issue**: There is a missing space in the class name for the form container (`space-y-8rounded-lg` should be `space-y-8 rounded-lg`), which may cause styling issues.

4. **Error Handling in Sign-Up Submission**: In the `onSubmit` function, there should be a fallback error message in case the server response does not include an error message. This ensures users receive clear feedback regardless of the server's response.

These issues affect the overall user experience and require immediate attention for a seamless sign-up process. I have made modifications to the code to address these concerns. Please review the changes for integration.

**Comment by MitulSonagara** [comment]
@chikatlarakesh go for it

**Comment by chikatlarakesh** [comment]
I have submitted a pull request for this issue, please check.
