### ISSUE TITLE
Adding github link of the website  in the Navbar

### ISSUE THREAD

**Issue by AswaniBolisetti** [MitulSonagara/truth-tunnel#141]
@MitulSonagara 
I would like to add a github link of Truth Tunnel website in the navbar using github icon, so that when user click it, the github link of Truth Tunnel will be opened
Kindly assign this task to me

**Comment by naitikhoriya1** [comment]
"I am working on adding a GitHub link of the Truth Tunnel website in the navbar using a GitHub icon. When users click on the icon, it will open the GitHub link of Truth Tunnel."

Let me know if you'd like further refinements!

**Comment by MitulSonagara** [comment]
@naitikhoriya1 

If you are working on this then you have to raise a issue ....

**Comment by MitulSonagara** [comment]
@AswaniBolisetti I am assigning this to you
