### ISSUE TITLE
[BUG]: Dark Advance Convert features

### ISSUE THREAD

**Issue by haseebzaki-07** [MitulSonagara/truth-tunnel#166]
**Describe the bug**
The advance convert features section remains dark even in the light mode . I want to fix it to match the theme of the website.

**To Reproduce**
1. Go to theme button
2. Click on Light
3. See the Advance convert features section

**Expected behavior**
Ideally the light theme should be reflected on the component

**Screenshots**
![Screenshot 2024-10-18 210348](https://github.com/user-attachments/assets/08abc751-40ec-4a7f-9210-5fef8b415398)
![Screenshot 2024-10-18 210515](https://github.com/user-attachments/assets/84e4a948-ffd5-4b97-a7b3-71e7a482d41a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MitulSonagara** [comment]
@haseebzaki-07 go for it
