### ISSUE TITLE
[FEATURE] Add password strength validation on signup page

### ISSUE THREAD

**Issue by jvkousthub** [MitulSonagara/truth-tunnel#170]
**Is your feature request related to a problem? Please describe.**
There should be password strength indicator like weak medium and good

**Describe the solution you'd like**
Add different colors like red orange and green describing strength

**Describe alternatives you've considered**

**Additional context**

**Comment by MitulSonagara** [comment]
@jvkousthub 

you can start working

**Comment by MitulSonagara** [comment]
There is already one issue regarding to this feature...
