### ISSUE TITLE
Bug: Middleware Authentication missing for /u/<user-name>

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#177]
- Even after logout, you can send messages to registered users.

![t2](https://github.com/user-attachments/assets/84c446a7-8eba-4f66-ad22-3c9a9b98ad09)

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

This is the feature of this project.... like anyone can send the message to the user with the link without creating any account or sign in.
