### ISSUE TITLE
Bug: Crypto library - infinite message loop in console on dashboard of some users

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#178]
![Animation4](https://github.com/user-attachments/assets/897e6565-ddbb-4d70-b406-16e1f2b31fb2)

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

what is the progress

**Comment by mehul-m-prajapati** [comment]
Debugged it yesterday, could not find solution. I will try again today

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

take your time

**Comment by MitulSonagara** [comment]
If you want you can change the encryption decryption method
