### ISSUE TITLE
[BUG] Unexpected Behavior of searching user and add suggestions 

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#180]
- Currently when user search with username that is not exists then it should show `not found` instead of  
![image](https://github.com/user-attachments/assets/26b86077-b0a4-464b-b66c-91855025f3e1)

- Create a side panel that will have a search bar with suggested users and search results as the current position do not suits.
- Side Panel like github side panel 
![image](https://github.com/user-attachments/assets/d933cc7c-e6c2-4e8d-b28e-810916299c86)

**Comment by mehul-m-prajapati** [comment]
@priyanshuverma-dev : this is similar issue that pointed out #176

**Comment by PriyanshuPz** [comment]
@mehul-m-prajapati I am extremely sorry about that but this issue is about UI/UX. not only on `debounce`. I didn't saw you supposed to add `debounce` you can add as I can revert `debounce` changes that I did if you want as it is only this much of code. Should I revert ??

```
  useEffect(() => {
    if (debouncedQuery) {
      handleSearch(debouncedQuery);
    }
  }, [debouncedQuery]);

```

**Comment by mehul-m-prajapati** [comment]
@priyanshuverma-dev : but, you can't open PR without assignment at first place

**Comment by PriyanshuPz** [comment]
Ah! Sorry about that friend as I asked Project Admin to do as I don't get much time to work. 
@mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
Yeah, if you don't have time, then don't work on issues which are not assigned to you. It is against guidelines. 

If it is allowed in this repo, then I will open all similar issues and close all pending PRs.

**Comment by PriyanshuPz** [comment]
Chill bro let me undo `deboucing` @mehul-m-prajapati 

![image](https://github.com/user-attachments/assets/fa60a73d-7a3a-404e-9739-2282e99434d9)

**Comment by mehul-m-prajapati** [comment]
> Chill bro let me undo `deboucing` @mehul-m-prajapati 
> 
> ![image](https://github.com/user-attachments/assets/fa60a73d-7a3a-404e-9739-2282e99434d9)
> 

Can you enlighten me on how PAs can explicitly assign tasks?
@priyanshuverma-dev

**Comment by PriyanshuPz** [comment]
@mehul-m-prajapati I have reverted the changes related to `debounce` 
 - https://github.com/MitulSonagara/truth-tunnel/pull/183/commits/5c571311a8b4b3b8b36506998c1d8371a4e71ac9

I am again sorry my intentions were not wrong to hurt you bro. ☮️

**Comment by mehul-m-prajapati** [comment]
Can you enlighten me on how PAs can explicitly assign tasks?
@priyanshuverma-dev

**Comment by PriyanshuPz** [comment]
I messaged PA personally on LinkedIn politely asked them. I am a good guy na. I don't blame on others for 2 lines of code

@mehul-m-prajapati

**Comment by mehul-m-prajapati** [comment]
I am not blaming anyone. I wanted to be clear on how a person can work on issues which are not assigned to him.
Now, I can also politely ask PAs on linkedin to work on issues.
Thanks for giving me a way.
@priyanshuverma-dev

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev  @mehul-m-prajapati 

Ya you can start working before i assign to you but please make sure that the issue you are creating that is not already exists... And if it is exist already then you have to comment on that issue.... Also if you are working without assigning then i will not guaranty you that this will be merged.
