### ISSUE TITLE
I want to add scroll animations to homepage using framer motion .

### ISSUE THREAD

**Issue by varma-101** [MitulSonagara/truth-tunnel#186]

**Comment by MitulSonagara** [comment]
@varma-101 

You can start working

**Comment by MitulSonagara** [comment]
@varma-101 

are you working on this??

If there is no progress then let me know i will assign this to another person

**Comment by Sawan-Kushwah** [comment]
@MitulSonagara can i work on this as he is not created any pull request since one week

**Comment by Sawan-Kushwah** [comment]
@MitulSonagara when i am doing changes in pages html but its not reflecting on website ? why
