### ISSUE TITLE
[BUG] Password length visible in sign-in page

### ISSUE THREAD

**Issue by Gauravtb2253** [MitulSonagara/truth-tunnel#187]
**Describe the bug**
Currently in the sign-in page, the length of the password is shown
It is not good for security reasons

**Expected behavior**
It should only tell invalid password

**Screenshots**
![image](https://github.com/user-attachments/assets/0b71545d-5286-4f09-9db3-b85f560a772c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by MitulSonagara** [comment]
@Gauravtb2253 

I dont think this is a bug for me... try creating any other issue

**Comment by Gauravtb2253** [comment]
The password length should be visible while registering and not while login
Like if someone tries to access other persons account he will get to know that the password is of x length
So it is not a good practice for security reasons to show the length in login page

**Comment by MitulSonagara** [comment]
@Gauravtb2253 

you can start working
