### ISSUE TITLE
[DOC] Updation in contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [MitulSonagara/truth-tunnel#193]
Wanted to do the following changes :-

Steps for submitting changes
Project setup instructions
Rules for code style
Code of conduct for respectful behavior
Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

**Comment by Nikhil0-3** [comment]
Please assign this work to me

**Comment by MitulSonagara** [comment]
These are not needed coz it is already there.... Thanks for raising the issue
@Nikhil0-3
