### ISSUE TITLE
Bug: Backend server crashes with error messages when username is invalid

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#197]
![image](https://github.com/user-attachments/assets/5edcdd8b-f3c0-4243-a8d6-5e74bb95dfb1)

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

Is this problem is happening while sign in or sign up

**Comment by mehul-m-prajapati** [comment]
@MitulSonagara : It happens when user signs in with invalid username/email. Although server runs fine, but we need to handle this case in backend.

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

Okay then go for it

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

You have good grip on frontend also?

**Comment by mehul-m-prajapati** [comment]
@MitulSonagara : yes, I can work on front-end issues as well.

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

check the issue #198

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 

there are many other issues also like ... fixing dark-light mode of contributor page and about page, adding backend to contact us page... etc

If you want to work on them then you can raise them

**Comment by mehul-m-prajapati** [comment]
@MitulSonagara : okay, I will raise other issues today and work on them tomorrow.

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati no problem i will assign it to you... don't forgot to upstream the branch coz i have made some changes
