### ISSUE TITLE
[UI] Constant Navbar on all the pages with responsivness

### ISSUE THREAD

**Issue by MitulSonagara** [MitulSonagara/truth-tunnel#198]
**Description**
Before sign in and after sign in navbar behavior is different. So, I want a person who can make consistent navbar for all the pages and after sign in you can change the position of change username and change key for the consistency.

**Comment by mehul-m-prajapati** [comment]
@MitulSonagara : We can add nav bar component and import it in all pages.

Please assign it to me.

**Comment by Hendrik69739** [comment]
Can i use react for that?

**Comment by mehul-m-prajapati** [comment]
**Things To be Worked Upon**
- Fix Navbar on all the pages
- Resolve profile dropdown bug
![p1](https://github.com/user-attachments/assets/07b54a83-4ba0-4cae-9dbe-12be44e66a09)
