### ISSUE TITLE
[Bug]/Signup feature not working properly

### ISSUE THREAD

**Issue by Mohith1490** [MitulSonagara/truth-tunnel#2]
#1 The signup feature cant send verification email

![Screenshot_2024-10-02_04_19_06](https://github.com/user-attachments/assets/fa45a593-1ce9-4541-bbaf-b52e5fbcc53c)

**Comment by MitulSonagara** [comment]
@Mohith1490 i am assigning this issue to you... go for it

Please read CONTRIBUTING.md before contributing.

Best of luck...

**Comment by MitulSonagara** [comment]
@Mohith1490 how much time will you take for solving it or i will assign it to someone else

**Comment by Mohith1490** [comment]
Hey i am busy with another stuff you can assign someone else for this issue

**Comment by PriyanshuPz** [comment]
@MitulSonagara May I work on this issue

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev go for it

**Comment by PriyanshuPz** [comment]
@MitulSonagara I think the error is because you are using `nodemailer` with `gmail` provider. As it has a limit to send email

**Comment by PriyanshuPz** [comment]
@MitulSonagara Should we use resend to send email or other smtp service??

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

At first i used resend api... But the main issue with resend is it can only send email to only that email with user is registered. Means if i create my account and use that api of resend then it will only allow to send email on my email not anyone else. 

So, if you have any other option then you can try.

**Comment by PriyanshuPz** [comment]
@MitulSonagara 
I have used resend to send emails but didn't understood what you are telling about.
If you are saying that it sends email with this email `onboarding@resend.dev` only.
Then you need to register a domain to make your custom email.

**Comment by MitulSonagara** [comment]
Ok then you can try... If it is working then its fine..

**Comment by PriyanshuPz** [comment]
Wait with gmail password you are using in nodemailer @MitulSonagara 

As I tried it is working fine

**Comment by MitulSonagara** [comment]
I didn't get what you are saying

**Comment by PriyanshuPz** [comment]
I have use these config ant it is working fine
```ts
const pass = process.env.EMAIL_PASS;
const user = process.env.EMAIL_USER;

// Create a transporter using SMTP details
const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user,
        pass,
    }
});
```

```env
# password generated with 2FA application
EMAIL_PASS=
EMAIL_USER=priyanshu.creator.dev@gmail.com
```

**Comment by PriyanshuPz** [comment]
@MitulSonagara I have also changed the constant email you used
```
            from: '"Truth-Tunnel" <mitul.songara.1612@gmail.com>', // sender address

```
So it can be changed with `.env`. 
And fixing problems like account is creating while username exists, etc.

**Comment by PriyanshuPz** [comment]
@MitulSonagara Do you want to migrate your project to use `prisma` ORM it can be better and scalable.
I can migrate it. If you want to you can create a issue about it and assign it to me.
