### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [MitulSonagara/truth-tunnel#200]
**Describe the bug**
The theme changer icon and the GitHub icon are overlapping with each other, and I need to fix this.

**To Reproduce**
1. Go to Navbar
2. look at right on top
 
 

**Screenshots**
 
![overlap2 0](https://github.com/user-attachments/assets/4fed19ef-a226-4a28-8ea9-e309eafb007c)

**Desktop (please complete the following information):**
 
 - Browser [e.g. chrome ]

**Comment by MitulSonagara** [comment]
@biswajit-sarkar-007 

Someone is working on whole navbar improvement so try searching for another issue..
