### ISSUE TITLE
[FEATURE] Enhance the UI of footer

### ISSUE THREAD

**Issue by biswajit-sarkar-007** [MitulSonagara/truth-tunnel#201]
**Is your feature request related to a problem? Please describe.**
 
On your website, I want to design the footer ,
1. The hover effect is not working on the footer's social media icons.
2. The "all rights reserved" text is not aligned correctly; I would like to fix it.

 

 **Screenshot**
 
![footer 4 0](https://github.com/user-attachments/assets/56b72b18-f94f-49be-8f0f-0b964f4c75ff)

**Comment by MitulSonagara** [comment]
@biswajit-sarkar-007 

Someone is already working with the footer try something else
