### ISSUE TITLE
ADD Backend for contact us page

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#202]
<img width="1402" alt="Screenshot 2024-10-21 at 4 16 25 AM" src="https://github.com/user-attachments/assets/c07e3688-29f8-4ec1-8dbc-2674b2ffb625">
Will design a model for users that submit the form and recored the details to the db

**Comment by SandipGyawali** [comment]
@shubhagarwal1 can i do it ??

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

Go for it

**Comment by AyushSharma72** [comment]
@MitulSonagara  if @shubhagarwal1 not working this issue can i do it i will make the pr by today only

**Comment by shubhagarwal1** [comment]
@AyushSharma72 PR is ready will push it by today
