### ISSUE TITLE
Fix Dashboad UI, and Enhance it 

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#204]
<img width="1430" alt="Screenshot 2024-10-21 at 4 22 20 AM" src="https://github.com/user-attachments/assets/e9291c7d-51e4-44f4-891d-081b29741d8d">
Improve things on the dashboard 
make it more like dashboaurd for now the things are scattered everywhere
hey @MitulSonagara please assign me this task

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

You can start working
