### ISSUE TITLE
ADD Sent message page, To keep track of sent messages

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#205]
After sending messages there is no place to see the sent message before the reply in order to which user has no track for sent messages
<img width="1401" alt="Screenshot 2024-10-21 at 4 27 24 AM" src="https://github.com/user-attachments/assets/a4cb4ef8-ca9d-456c-9706-b3485003c412">

I propose to add a sent message page 
hey @MitulSonagara please assign me this task

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

Not planned yet
