### ISSUE TITLE
[BUG]Search user is not working 

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#206]
<img width="1440" alt="Screenshot 2024-10-21 at 4 34 55 AM" src="https://github.com/user-attachments/assets/5ff8be13-a524-4116-80a8-97e40d4bdb55">
<img width="1438" alt="Screenshot 2024-10-21 at 4 35 08 AM" src="https://github.com/user-attachments/assets/796b523f-6a78-45e4-8928-cc905e7bebb8">
Shows in suggest but when searched do not come 

I have logged in two accounts and searched for the account the account is not visible to the search list,
Hey @MitulSonagara please assign me this task

**Comment by MitulSonagara** [comment]
@shubhagarwal1 You can start working
