### ISSUE TITLE
Fix Bugs

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#207]
1. Last msg remianing in the stack did not remove
2. Loading state on trash icon on single message delete when message is to be deleted
3. Add Loading state to accept message toggle

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

go for it

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

After clicking delete all messages, messages are getting deleted but we have to refresh the page so fix this ... this will help you
