### ISSUE TITLE
Enhance Readme

### ISSUE THREAD

**Issue by souvikpramanikgit** [MitulSonagara/truth-tunnel#21]
Hi,

I’ve been exploring the project and appreciate the work you’ve done so far. I’d like to propose an update to the README.md file. Here are a few ideas I have in mind:

I want to add some animations (icons), change the alignment of text and few more changes...

I believe these updates could enhance user understanding and engagement with the project. If you're open to it, I’d love to contribute.

I’m committed to continually improving the quality of our documentation.

Thank you!

**Comment by MitulSonagara** [comment]
@souvikpramanikgit Go for it...

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.

**Comment by souvikpramanikgit** [comment]
@MitulSonagara when did you go you sleep

**Comment by souvikpramanikgit** [comment]
already it's 3 am in india
