### ISSUE TITLE
[FEATURE] Add Missing Meta Tags, Sitemap, Robots.txt for SEO Enhancement

### ISSUE THREAD

**Issue by itshivams** [MitulSonagara/truth-tunnel#213]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag
@MitulSonagara  Please assign this issue to me (@myselfshivams).

Labels:

GSSoC
Hacktoberfest

**Comment by MitulSonagara** [comment]
@myselfshivams 

You can start working
