### ISSUE TITLE
[FEATURE] Create a Custom 404 Page for Better User Experience

### ISSUE THREAD

**Issue by itshivams** [MitulSonagara/truth-tunnel#214]
Currently, when users encounter a broken or non-existent link, the website shows the default 404 error page. To enhance the user experience, we should create a custom 404 page with a user-friendly design and helpful navigation options (e.g., a link back to the homepage or other important sections). This will help guide users when they land on a missing page, improving overall usability.

Labels:

gssoc
hacktoberfest
@MitulSonagara l Please assign this task to me (@myselfshivams).

**Comment by MitulSonagara** [comment]
@myselfshivams you can start working

**Comment by dev129** [comment]
Hi @MitulSonagara , here is your design 
![image](https://github.com/user-attachments/assets/43fb2853-4684-4963-94e7-ec7c389fdc67)
you assign me this task , I shall raise PR, it will take less than 4 mins with image of your logo instead of any random image.

**Comment by MitulSonagara** [comment]
@myselfshivams 

Are you working on this? How much time you will take

**Comment by dev129** [comment]
@MitulSonagara 
As you may have noticed for past 7 hours, he hasn't  replied while I would ,within this time frame I could have completed the error page make you website running.

**Comment by MitulSonagara** [comment]
@dev129 

you can work on this i am assigning this to you

**Comment by dev129** [comment]
Hi @MitulSonagara 
This is the light mode : 
![image](https://github.com/user-attachments/assets/11b58bd1-ad3f-464a-9303-ecc2719753eb)
and this is dakr mode : 
![image](https://github.com/user-attachments/assets/16e5bf8f-a9f6-4d1f-914c-1a662c2e4b85)

**Comment by dev129** [comment]
@MitulSonagara , shall I raise the PR or not ?

**Comment by MitulSonagara** [comment]
@dev129 

ya you can raise the PR but in dark mode also use the same logo full logo

**Comment by dev129** [comment]
Hi @MitulSonagara , please check my PR and lt me know.
