### ISSUE TITLE
[BUG] Text not visible in light mode

### ISSUE THREAD

**Issue by Bhum-ika** [MitulSonagara/truth-tunnel#217]
**Describe the bug**
The text color is same in both themes due to which it is not visible in light theme
![image](https://github.com/user-attachments/assets/c5a17128-c630-4302-a9e0-23e8e22f27ba)

Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by mehul-m-prajapati** [comment]
Already fixed #216
