### ISSUE TITLE
[FEATURE]Add testimonial for user trust !

### ISSUE THREAD

**Issue by Sawan-Kushwah** [MitulSonagara/truth-tunnel#229]
By adding stronger testimonials, we can build user trust, improve credibility, and significantly enhance the overall experience on our platform

![Screenshot 2024-10-18 191732](https://github.com/user-attachments/assets/52a65bb1-cc7d-49ce-81b1-77586772c118)

Something like this i can redesign it according to website theme and make it more beautiful
on clicking on the arrow cards slide with an animation with create great user impact

**Comment by MitulSonagara** [comment]
@Sawan-Kushwah 

You can start working but make sure it matches the overall UI of the website with dark and light mode both.
