### ISSUE TITLE
[UI]Term and condition page enhancement

### ISSUE THREAD

**Issue by Sawan-Kushwah** [MitulSonagara/truth-tunnel#231]
![image](https://github.com/user-attachments/assets/fb30077f-48e9-43a4-8014-1821207b6641)

as you can see it not looking good i can enhance its UI to look even more better

**Comment by MitulSonagara** [comment]
@Sawan-Kushwah 

You can start working

**Comment by AswaniBolisetti** [comment]
@Sawan-Kushwah Hey did you complete this, or else I would like to work on it
@MitulSonagara

**Comment by Sawan-Kushwah** [comment]
@AswaniBolisetti i will make PR today
