### ISSUE TITLE
Styling the default sroll bar

### ISSUE THREAD

**Issue by AswaniBolisetti** [MitulSonagara/truth-tunnel#237]
@MitulSonagara 
The default scroll bar is not matching with the website and also the black border is making the website not to look professional so i would like to remove it
Could you please assign it to me

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Could you please assign this to me

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

you can start working
