### ISSUE TITLE
Adding FAQ page

### ISSUE THREAD

**Issue by AswaniBolisetti** [MitulSonagara/truth-tunnel#238]
@MitulSonagara 
I would like to add one more item in the navbar i.e., FAQ, by clicking on it , it will display the faq page
I would like to add a seperate FAQ page
Could you please assign it to me

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Kindly assign this to me

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

Not planned yet
