### ISSUE TITLE
Enhancing Home page in mobile view

### ISSUE THREAD

**Issue by AswaniBolisetti** [MitulSonagara/truth-tunnel#239]
@MitulSonagara 
In mobile view, the home page is not looking good, I would like to enhance it
Could you please assign it to me

![mobile](https://github.com/user-attachments/assets/0435afd3-0dd4-4360-a9d1-6582cde5f1a2)

**Comment by AswaniBolisetti** [comment]
@MitulSonagara 
Could u please assign this to me

**Comment by MitulSonagara** [comment]
@AswaniBolisetti 

Someone is already working on this
