### ISSUE TITLE
[BUG] : Message Decryption failure

### ISSUE THREAD

**Issue by mehul-m-prajapati** [MitulSonagara/truth-tunnel#244]
![c1](https://github.com/user-attachments/assets/824d6663-1bf0-45a2-be84-6a26107fe945)

**Comment by PriyanshuPz** [comment]
@mehul-m-prajapati Try to add private key again 😅

**Comment by mehul-m-prajapati** [comment]
Where is the option to add key

**Comment by PriyanshuPz** [comment]
Click on user profile button,
You will see option to change key.
@mehul-m-prajapati

**Comment by PriyanshuPz** [comment]
@mehul-m-prajapati 
BTW Wait for this PR #233 as it fixes this issue to adding long encryption key to a simple unlocking secret passphrase

**Comment by MitulSonagara** [comment]
@mehul-m-prajapati 
@priyanshuverma-dev 

IDK why this issue is solved automatically...
![image](https://github.com/user-attachments/assets/ff196907-4f7c-457c-aab5-ac4e7b339af0)

There is some problem in PR #233 check it

**Comment by mehul-m-prajapati** [comment]
Okay will check and update you @MitulSonagara
