### ISSUE TITLE
[BUG] Not being able to verify the otp after signing up

### ISSUE THREAD

**Issue by ShivanshPlays** [MitulSonagara/truth-tunnel#245]
**Describe the bug**
There is some issue in the flow of control for new users signing up. I am facing the same

**To Reproduce**
try to signup as a new user

**Expected behavior**
seamless otp verification

**Screenshots**
![image](https://github.com/user-attachments/assets/1700e994-6ef6-47ba-a11f-e553f0cbd38f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MitulSonagara** [comment]
@ShivanshPlays 

OTP verification is working very well. try again
