### ISSUE TITLE
[BUG] Hero section mobile responsiveness issue

### ISSUE THREAD

**Issue by ShivanshPlays** [MitulSonagara/truth-tunnel#247]
**Describe the bug**
check the alignment of the picture and text

**Expected behavior**
proper alignment

**Screenshots**
![image](https://github.com/user-attachments/assets/1ff9e322-bd3d-49e8-b05c-0aef88f27e5e)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MitulSonagara** [comment]
@ShivanshPlays 

Someone already working on this
