### ISSUE TITLE
[UI] Better contributors page

### ISSUE THREAD

**Issue by ShivanshPlays** [MitulSonagara/truth-tunnel#248]
**Description**
A clear and concise description of the proposed UI change. What part of the UI needs to be changed, and why?

The contributors page has simple cards, We can do better.

**Screenshots**
![image](https://github.com/user-attachments/assets/8881cee0-50f9-48b4-99ae-257662ddd64d)

**Additional Context**
we can add better design like a grid in medium and above screens and flex on smaller ones, with better styling of the page, I can also add a showcase for top contributors like gssoc page:
![image](https://github.com/user-attachments/assets/e8bf4db8-6178-4921-98fa-4efeb431bdfc)

**Impact**
Attractive UI for contributors page

**Related Issues**
Link to any related issues, discussions, or feature requests that are relevant to this UI change.

**Comment by MitulSonagara** [comment]
@ShivanshPlays 

You can start working... but make sure it will adapt the overall UI of the website

**Comment by ShivanshPlays** [comment]
@MitulSonagara I will make sure that it is consistent with the existing UI
