### ISSUE TITLE
[UI] No proper alignment in hero section text

### ISSUE THREAD

**Issue by nishtha-902** [MitulSonagara/truth-tunnel#250]
**Description**
No proper alignment in hero section text

**Current Behavior**
Text is shifted right

**Proposed Behavior**
Text must be aligned to left and button too

**Screenshots**
![image](https://github.com/user-attachments/assets/5bc292f0-39a4-464c-9304-2824093882c9)

**Comment by MitulSonagara** [comment]
@nishtha-902 

Someone is already working on this
