### ISSUE TITLE
ADD table of Content on Readme File

### ISSUE THREAD

**Issue by alo7lika** [MitulSonagara/truth-tunnel#251]
## Description

**ADD table of Content on Readme File**

**Affected Pages**:
- [x] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [ ] Other (please specify)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Adding a table of contents (TOC) to the README file will enhance the navigation experience for users, allowing them to quickly find relevant sections. This is particularly helpful for larger README files with multiple sections.

## Suggested Improvements

- **Table of Contents Format**: Consider using Markdown links for each section of the README, allowing users to jump directly to the relevant part of the document.
- **Section Headings**: Ensure all major sections of the README are included in the TOC for clarity.
- **Update Style Consistency**: Maintain consistent formatting throughout the README for a professional appearance.

**Comment by alo7lika** [comment]
Assign me the work under GSSOC EXT 24 AND HACKTOBERFEST @MitulSonagara

**Comment by MitulSonagara** [comment]
@alo7lika 

please refer already created issue first before creating new one
issue #226
