### ISSUE TITLE
Adding Password hide/ show button

### ISSUE THREAD

**Issue by Sourabh782** [MitulSonagara/truth-tunnel#26]
### Is your proposal related to a problem?

Adding a password show/hide button so user can cross check

(Write your answer here.)

### Describe the solution you'd like

I wanted to add a button to hide/show password

(Describe your proposed solution here.)

### Describe alternatives you've considered
![image](https://github.com/user-attachments/assets/5b7f4cfd-0eb7-44c3-a2a7-734702317c6b)

**Comment by MitulSonagara** [comment]
@Sourabh782 go for it
