### ISSUE TITLE
Adding forgor password feature (Backend and frontend)

### ISSUE THREAD

**Issue by Sourabh782** [MitulSonagara/truth-tunnel#27]
### Is your proposal related to a problem?

If user forgets his password theres no way to login in his account

(Write your answer here.)

### Describe the solution you'd like

I wanted to add forget password functionality, so user can change his passsword

(Describe your proposed solution here.)

![image](https://github.com/user-attachments/assets/9c418643-355b-4e3c-9144-e07233a6a954)

**Comment by MitulSonagara** [comment]
@Sourabh782 Go for it

**Comment by Sourabh782** [comment]
@MitulSonagara i am having a problem regarding mail, i have added backend routes but mail is giving a error, can you help resolve it?
![image](https://github.com/user-attachments/assets/7a737658-eb64-453d-bd16-2480c3caabcb)

i am sure its some setup error
