### ISSUE TITLE
[DOC] : Enhancement Of Contributing.md

### ISSUE THREAD

**Issue by milansamuel609** [MitulSonagara/truth-tunnel#275]
## Description

The contributing.md file is not in a structured manner. Also some sections are missing. I can enhance it in a well structured manner with proper details and some additional sections also that will make the contributors easier to contribute.

**Affected Pages**:
- [ ] README.md
- [ ] Installation Guide
- [ ] Configuration Guide
- [x] Other (Contributing.md)

## Type of Documentation Change

- [x] Update existing documentation
- [ ] Add new documentation
- [ ] Remove outdated or redundant documentation
- [ ] Other (please specify)

## Additional Context

Please add any other context or screenshots about the documentation issue or suggestion here.

## Suggested Improvements

Wanted to do the following changes :-

1) Enhancing the complete project structure
2) Modify the code of conduct alignment in the document
3) Add a section for star our repository in the top
4) Add a section for help with the basics
5) Add a section for doing the first pull request
6) Add additional method of contributing through GitHub desktop section
7) Add a good practices section from which everyone can understand the correct way of writing codes
8) Add the pull request rules section
9) Add the thank you section

---

**Comment by MitulSonagara** [comment]
@milansamuel609 

I can assign this to you but merging of the PR will be based on the content

**Comment by milansamuel609** [comment]
> @milansamuel609
> 
> I can assign this to you but merging of the PR will be based on the content

Sure 👍
