### ISSUE TITLE
Fix Navbar UI and Move "Made with ❤️ by Mitul Sonagara © 2024" to Footer

### ISSUE THREAD

**Issue by itshivams** [MitulSonagara/truth-tunnel#3]
- Navbar UI: The current navbar needs UI improvements to ensure better design, responsiveness, and alignment across different devices. 

- Footer Component: Move the text "Made with ❤️ by Mitul Sonagara © 2024" from the current location to a dedicated footer component.

**Please assign this task to me (myselfshivams).**

**Comment by MitulSonagara** [comment]
@myselfshivams thanks for contributing to my project.

Please make sure to read CONTRIBUTING.md before contributing

**Comment by MitulSonagara** [comment]
@myselfshivams 

Are you working on this??

**Comment by itshivams** [comment]
> @myselfshivams
> 
> Are you working on this??

Yeah, I am working

**Comment by MitulSonagara** [comment]
@myselfshivams 
after no response from long time i am closing this issue
