### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by Meetjain1** [MitulSonagara/truth-tunnel#30]
Dear Project Admin @MitulSonagara 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by MitulSonagara** [comment]
@Meetjain1 thank you for letting me know my mistake... i have made the necessary changes.

**Comment by Meetjain1** [comment]
@MitulSonagara which changes you have made I can't see any correct labels on merged prs

**Comment by MitulSonagara** [comment]
@Meetjain1 

Ya i have that question, I asked it on discord also...

If i am labeling the issues then i need to add labels to PR also??

**Comment by Meetjain1** [comment]
> @Meetjain1
> 
> Ya i have that question, I asked it on discord also...
> 
> If i am labeling the issues then i need to add labels to PR also??

@MitulSonagara labels on prs is must as points are fetched from merged prs itself

**Comment by MitulSonagara** [comment]
@Meetjain1 thank you I will make sure to not make this mistake again.

**Comment by MitulSonagara** [comment]
@Meetjain1 I have made changes... can you review it. Please let me know if any other mistakes are there

**Comment by Meetjain1** [comment]
@MitulSonagara Yes it's correct,  Thankyou for the changes!

**Comment by Meetjain1** [comment]
@MitulSonagara you use wrong label of gssoc 
correct is "gssoc-ext" as I mentioned .
please fix it

**Comment by Meetjain1** [comment]
@MitulSonagara that is no 'd' in ext .

**Comment by MitulSonagara** [comment]
@Meetjain1 I made the required changes.

**Comment by Meetjain1** [comment]
> @Meetjain1 I made the required changes.

@MitulSonagara Perfect !

**Comment by MitulSonagara** [comment]
@Meetjain1 

Thank you for your guidance and correcting my mistakes.
