### ISSUE TITLE
Add loader while sign up or sign in

### ISSUE THREAD

**Issue by MitulSonagara** [MitulSonagara/truth-tunnel#32]
Add loader to website when user tries to sign up or sign in. Loader must be complement with the overall UI of the website.

**Comment by GaneshLadaskar** [comment]
Hii,
I am Ganesh looking to contribute to the frontend project can you assign me this issue to solve your issue as I am passionate to contribute in open source.

**Comment by harish08102004** [comment]
hey @MitulSonagara I can work on this.

**Comment by MitulSonagara** [comment]
@GaneshLadaskar 
@harish08102004 

Anyone of you before done this type of work like adding loader to your website.
And you are experienced with react, next.js and typescript

**Comment by harish08102004** [comment]
hey @MitulSonagara ,
I'm currently studying Software Engineering at Kalvium, and while I haven't built this feature before, I'm excited to take it on. I have access to mentors and peers with experience in similar tasks, so this would be a great opportunity for me to learn and contribute.

**Comment by MitulSonagara** [comment]
@harish08102004 go for it. But make sure not to break the consistency of the project

**Comment by harish08102004** [comment]
yeah sure.

**Comment by GaneshLadaskar** [comment]
As I am new in this technology field, I haven't done this project before
but try my best to fulfil your requirements.

**Comment by MitulSonagara** [comment]
@GaneshLadaskar 
@harish08102004 

you both can do this.
Whoever makes PR  first and it will good with UI then i will merge that.

**Comment by harish08102004** [comment]
![image](https://github.com/user-attachments/assets/302ff36c-92a6-4ebe-b67b-e9885bef1b7d)
Hey i'm not able to sign up.

**Comment by MitulSonagara** [comment]
@harish08102004 

Make sure you are using valid email address and there are major changes in project in latest PR so first upstream the project SetUp new environment variables then try to do this
