### ISSUE TITLE
Dockerize the Application

### ISSUE THREAD

**Issue by PankajKumardev** [MitulSonagara/truth-tunnel#34]
I want to add Dockerfile to the root of the project. A Dockerfile is a text file of instructions which are used to automate installation and configuration of a Docker image .
Adding Dockerfile to the root of the project will encourage image formation of the application using Docker and running the image in one's local environment without installing the dependencies.

[x ] I am contributing under GSSoC-ext
[x ] I am contributing under hacktoberfest
[x ] I follow contribution guidelines

**Comment by MitulSonagara** [comment]
This issue is already there... Make sure you first check the existing issue and after then only create new issue.
