### ISSUE TITLE
[Feat]: Use Prisma instead of Raw mongodb

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#37]
### Is your proposal related to a problem?

Using Raw mongodb is not that efficient so,
Do you want to migrate your project to use `prisma` ORM it can be better and scalable.
I can migrate it. If you assign this issue to me.

### Describe the solution you'd like

I will use Prisma ORM and migrate everything to that including authentication

### Describe alternatives you've considered

It is going to be alternative of Raw mongodb schemas and a connection function that is not efficient in long run.

### Additional context

It can be very easy to use Prisma and creating new model is also easy with typesafety

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev  go for it
