### ISSUE TITLE
Bug: Validation Error on Register page does not go even after user changes it.

### ISSUE THREAD

**Issue by ZayedShahcode** [MitulSonagara/truth-tunnel#38]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

When a user is entering his/her username on register form, and if the username is already taken we get a validation error in red text below it. But if the user changes its user name, the validation error must also change after validating the new username

### Steps to Reproduce

1. Go to signup page
2. Type a username that's already taken and get the validation error.
3. change the username to something unique.
4. Validation error still doesn't go.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

### Actual Results

When a user is entering his/her username on register form, and if the username is already taken we get a validation error in red text below it. But if the user changes its user name, the validation error must also change after validating the new username

### Expected Results

if the user changes its user name, the validation error must also change after validating the new username

### Technical details

https://github.com/user-attachments/assets/1aa13f17-0c46-4734-af64-45fd04885470

**Comment by MitulSonagara** [comment]
@ZayedShahcode 

Go for it
