### ISSUE TITLE
Google Authentication

### ISSUE THREAD

**Issue by ayushku634** [MitulSonagara/truth-tunnel#42]
### Is your proposal related to a problem?

Currently, users can only sign up using an email and password, which might not be the most convenient option. Many users prefer social logins for a faster, seamless experience, and adding Google Authentication would simplify the registration process for them.

### Describe the solution you'd like

Integrating Google OAuth 2.0 to allow users to sign up and log in using their Google account. This would reduce the friction during the sign-up process and improve the overall user experience.

### Describe alternatives you've considered

Other social logins such as GitHub or Facebook, but Google Authentication is the most commonly used and widely trusted option, making it a better fit for this project’s first implementation of social login.

### Additional context

<img width="410" alt="Screenshot 2024-10-08 at 8 18 28 PM" src="https://github.com/user-attachments/assets/1ce1c119-21d0-4be0-aebb-deee0d6da6ec">
The Google Authentication button could be placed beneath or alongside the current sign-up form, similar to what other platforms use for OAuth-based logins.

### Requirement/Document

A basic implementation of Google OAuth 2.0 can be found in the Google Developers documentation which could guide the integration process. This will require backend handling of OAuth tokens and secure user data storage.

**Comment by ayushku634** [comment]
@MitulSonagara Assign me this task, I want to add this feature.

**Comment by MitulSonagara** [comment]
@ayushku634 

This issue is already there and someone is already working on this. 
Refer issue #9
