### ISSUE TITLE
Error in login even if email and passoword are correct

### ISSUE THREAD

**Issue by AyushSharma72** [MitulSonagara/truth-tunnel#43]
there is issue in login even if correct email and password are provided

see here:
![Screenshot (180)](https://github.com/user-attachments/assets/aac25856-fb13-4024-a105-146c8862c223)

![Screenshot (182)](https://github.com/user-attachments/assets/5fd1459b-a698-4b86-a1e4-7948d3c15147)

![Screenshot (185)](https://github.com/user-attachments/assets/2248c90f-ca3c-4439-83e3-ce62913248f8)

i also tried login with useranme the same issue is coming 

please assign this issue to me @MitulSonagara

**Comment by MitulSonagara** [comment]
@AyushSharma72 

Okay you can work on this. I am assigning it to you. But this problem is only with email login. If i use username for login then it is working totally fine. Hope this will help you to fix it.

**Comment by AyushSharma72** [comment]
> @AyushSharma72
> 
> Okay you can work on this. I am assigning it to you. But this problem is only with email login. If i use username for login then it is working totally fine. Hope this will help you to fix it.

I don't remember may there is error with username as well i will update you

**Comment by PriyanshuPz** [comment]
@MitulSonagara This issue is solved with 
- #40

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

That's Great brother...

@AyushSharma72 so there is not any error more so you can stop working on this
