### ISSUE TITLE
Swiper need to fixed according to size of the window

### ISSUE THREAD

**Issue by RahulScripted** [MitulSonagara/truth-tunnel#44]
# Is your proposal related to a problem?
Yes, the current Swiper slider is improper and does not effectively adapt to different screen sizes. On smaller screens, the slides are either cut off or appear too small, which negatively impacts the user experience. The slider should resize dynamically according to the screen size to maintain visual appeal and usability.

# Describe the solution you'd like
Implement a responsive Swiper slider that automatically adjusts the number of visible slides and their dimensions based on the screen size. This can be achieved by using Swiper’s built-in breakpoints configuration to define custom settings for various screen sizes.

**Comment by MitulSonagara** [comment]
@RahulScripted 

you can work on this
