### ISSUE TITLE
[Feature]: Add a theme toggle and Light mode

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#48]
### Is your proposal related to a problem?

Theme toggle Switch and light mode

### Describe the solution you'd like

Use `next-themes` and add light theme

### Describe alternatives you've considered

I will use `shadcn-ui` and `next-themes`

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by PriyanshuPz** [comment]
@MitulSonagara May I implement this fix

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

You can work on it
