### ISSUE TITLE
[Feature]: Fetch messages from Database and show on with new look

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#50]
### Is your proposal related to a problem?

Only three static messages are shown

### Describe the solution you'd like

Add messages from database and redesign Page for new MODERN AGE!

### Additional context

(Write your answer here.)

### Requirement/Document

(Share it here.)

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

You are trying to improve home page or user dashboard..

**Comment by PriyanshuPz** [comment]
@MitulSonagara  Yes, 
- New Home Page to show messages and 
- Dashboard for easy navigation and 
- fixing constant messages shown

Three fixes

**Comment by MitulSonagara** [comment]
Home page carousel messages are static dummy messages... We can't show any user messages there due to privacy. You can change the UI.

**Comment by PriyanshuPz** [comment]
We will not show username. Show only message.
@MitulSonagara

**Comment by MitulSonagara** [comment]
How many messages will you fetch... And from that what if any message will contain any confidential information.

**Comment by PriyanshuPz** [comment]
@MitulSonagara 
The Platform is for 1v1 Chat or Open Chat to everyone.
Let me know as that will help in adding new features

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

It is like anyone can send message to particular person using their private message link. And this messages will be anonymous for any user. So all the senders don't have to worry about no one will know that who send this message. Also, sent messages only read by the receiver to which sender send the message, no one else read that message

**Comment by PriyanshuPz** [comment]
@MitulSonagara 
It's like we have a user profile. On which others can message anonymously.

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev yes
