### ISSUE TITLE
Add a FAQ Section on the page

### ISSUE THREAD

**Issue by akshjswl** [MitulSonagara/truth-tunnel#52]
### Is your proposal related to a problem?

(Write your answer here.)

### Describe the solution you'd like

(I want to implement a comprehensive Help and Support feature for the Truth-Tunnel Web Application. This will include:

FAQ Section: A categorized list of common questions and clear answers to help users quickly find information.)

please assign this issue to me...

**Comment by MitulSonagara** [comment]
@akshjswl 

You can start working...

**Comment by MitulSonagara** [comment]
@akshjswl 

After no response from long time i am closing this issue
