### ISSUE TITLE
UIUX improvement 

### ISSUE THREAD

**Issue by Adrija05** [MitulSonagara/truth-tunnel#53]
### Is your proposal related to a problem?

The current UI/UX of the "Home page" page is poorly designed, making it unappealing and difficult to use. This not only discourages users from signing up but also significantly reduces engagement. A poor first impression on this crucial page can result in potential users abandoning the sign-up process altogether.

### Describe the solution you'd like

I would like to resolve the issue where the page isn't opening and redesign the entire UI/UX. My goal is to create a more intuitive and visually appealing sign-up experience by:

1)Simplifying the layout
2)Incorporating clear and user-friendly input fields with proper validation
This approach will make the process smoother and more attractive, ultimately increasing user engagement.

### Describe alternatives you've considered

UI Frameworks: I researched the use of UI frameworks like Material UI and Ant Design to bring a more modern and responsive design to the Home page. 
User Experience Best Practices: I also explored best practices for form design and user experience, such as keeping forms short and simple, adding clear input labels

### Additional context

I just want to improve the uiux to make it responsive according to the user experience so that they can use it seamlessly.

### Requirement/Document

(Share it here.)

**Comment by MitulSonagara** [comment]
@Adrija05 

Go for it

**Comment by Adrija05** [comment]
Thankyou for assigning this issue to me I will try to do my best.

**Comment by Adrija05** [comment]
<img width="1470" alt="Screenshot 2024-10-13 at 4 52 05 PM" src="https://github.com/user-attachments/assets/269e1091-188d-475b-bb1e-835e3f55e27e">
can you please resolve this orelse I'm unable to run this file.

**Comment by MitulSonagara** [comment]
@Adrija05 
 
you have to create your google credentials for google auth.

you can follow this tutorial 
https://www.youtube.com/watch?v=1TvrgUdlzAc

you have to add
GOOGLE_CLIENT_ID
and
GOOGLE_CLIENT_SECRET
in .env file

**Comment by Adrija05** [comment]
Okay thankyou

**Comment by MitulSonagara** [comment]
@Adrija05 

After no response from long time i am closing this issue
