### ISSUE TITLE
Modification of README.md file & Creation of LICENSE File for project

### ISSUE THREAD

**Issue by rajdeepchakraborty-rc** [MitulSonagara/truth-tunnel#56]
### 1) Incomplete animated line separators and add GSSoC 2024 Extended accepted banner
There are sections in the README.md file where the line separators are missing! I would like to fill those gaps and also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.

### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/cd0b1857-dcab-4c74-a33f-76e7f14c181a)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors. I would like to update it and try to automate the process.

## 2. Addition of a LICENSE File to the project
The presence of a LICENSE file explicitly states the terms under which the code can be used, modified, and shared. If a project does not have a LICENSE file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.

### 1) Add  the incomplete animated line separators and add GSSoC 2024 Extended accepted banner
There are sections in the README.md file where the line separators are missing! I would like to fill those gaps and also add the GSSoC 2024 Extended accepted image for Contributors to know that this repository is officially accepted for GSSoC contribution.

![image](https://github.com/user-attachments/assets/4dd78a96-9066-4614-bba6-58dd654c3bf7)

### 2) Replace the Contact section  with a **Team section**
The present Contact section in the **README.md** file is not looking attractive:
![image](https://github.com/user-attachments/assets/cd0b1857-dcab-4c74-a33f-76e7f14c181a)

The Team section will look more organized and readable and let the Contributors know whom to contact if they face any issues.

![image](https://github.com/user-attachments/assets/fae867de-c89c-441c-82ba-4b0d6374ef39)

### 3) Updation of the Contributors section
The current Contributors section is the README.md file is not updated to the latest Contributors.
![image](https://github.com/user-attachments/assets/d3cd79fa-0958-43bb-9774-591815f261bc)

 I would like to update it and try to automate the process.
![image](https://github.com/user-attachments/assets/f4d4f935-8da5-4f4f-90e3-d1bd30b8a7a0)

## 2. Addition of a LICENSE File to the project
If a project does not have a **LICENSE** file, it implies that the author has not granted any rights to others, and legally, no one has permission to use, distribute, or modify the code.
So, adding a **LICENSE** file is a best practice for open-source projects. I have added the LICENSE to your project and attached a reference image below to help you review the PR.
MIT LICENSE Reference:
![image](https://github.com/user-attachments/assets/c86b485a-b0c7-4717-8b0b-1a24191a3675)

### Describe alternatives you've considered

N.A.

### Additional context

N.A.

### Requirement/Document

N.A.

**Comment by rajdeepchakraborty-rc** [comment]
@MitulSonagara Thanks for assigning me the issue. I would also like to ask whether the issue shouldn't be assigned **level2**? Since I am updating quite a lot of features and also adding the LICENSE file?

**Comment by MitulSonagara** [comment]
I have updated the label you can start working

**Comment by rajdeepchakraborty-rc** [comment]
> I have updated the label you can start working

I have already started! Thanks for updating the label. I will update you about the progress of the work. Please keep a check for this issue.

**Comment by rajdeepchakraborty-rc** [comment]
@MitulSonagara I wanted to update you regarding the work. I have added the Team section. Here's how it looks for you:

- Before
![image](https://github.com/user-attachments/assets/0e516b81-a5be-4e60-a8ba-27f110431229)


- After
![image](https://github.com/user-attachments/assets/1199e782-d3cc-4310-b851-4461351e93d7)

I also added a **Support Project** section.

**Comment by rajdeepchakraborty-rc** [comment]
This is the update regarding the contributor mention section:

- Before
![image](https://github.com/user-attachments/assets/200fec7a-c9ae-45fc-8eb0-1a12f7a2d94c)

- After
![image](https://github.com/user-attachments/assets/5398850d-456b-496b-b224-b49faabf6fdb)

**Comment by rajdeepchakraborty-rc** [comment]
I am done with the major changes. I will do the finishing touches and then open a PR and let you know.

**Comment by rajdeepchakraborty-rc** [comment]
The License has also been added:
![image](https://github.com/user-attachments/assets/191c49ef-6b43-489a-8cdc-bb8fd6b90d4b)

**Comment by rajdeepchakraborty-rc** [comment]
Since your project is accepted for both Hacktoberfest and GSSoC Extended thus I have added the following banners:
![image](https://github.com/user-attachments/assets/32eb7405-41d6-4171-b6b7-ca2d014c842e)

**Comment by rajdeepchakraborty-rc** [comment]
I am done with the work. I will open a PR soon and inform you.

**Comment by MitulSonagara** [comment]
@rajdeepchakraborty-rc Nice work

**Comment by rajdeepchakraborty-rc** [comment]
> @rajdeepchakraborty-rc Nice work

@MitulSonagara Thanks a lot for the appreciation. Also sorry for the delay. I had a power cut at my place.
