### ISSUE TITLE
Accept message slide in button

### ISSUE THREAD

**Issue by Joshna907** [MitulSonagara/truth-tunnel#59]
So, when we turn off or turn on the accept message sliding button it gives notifications but when i do it again there is another notification on top of it which makes it messy so I could remove the first notification and then when turn on or off the second notification would come it wont be like a stack 
![image](https://github.com/user-attachments/assets/24e44513-623d-4add-960a-eebf91a54868)

**Comment by Joshna907** [comment]
@MitulSonagara Please assign me this to make the necessary changes

**Comment by MitulSonagara** [comment]
@Joshna907 you can start working

**Comment by MitulSonagara** [comment]
@Joshna907 

After no response from long time i am closing this issue
