### ISSUE TITLE
ADD: About page to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [MitulSonagara/truth-tunnel#61]
I propose to add a about us page on the websit eso that, we can enhae the website informative and more contributing to the solution.

**Comment by MitulSonagara** [comment]
@shubhagarwal1 go for it

**Comment by shubhagarwal1** [comment]
hey @MitulSonagara thank you for assigning me the task, will complete it by tonight

**Comment by shubhagarwal1** [comment]
hey @MitulSonagara can you help me in project setup

**Comment by MitulSonagara** [comment]
@shubhagarwal1 

Sure bro

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1
> 
> Sure bro

can we connect on discord, may i know your discord id please

**Comment by MitulSonagara** [comment]
mitul2003

**Comment by MitulSonagara** [comment]
@shubhagarwal1 give me yours

**Comment by MitulSonagara** [comment]
https://discord.gg/EubkB7RE

@shubhagarwal1 join this server

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 give me yours

harry_8409
