### ISSUE TITLE
Issue: Login Button on Signup Page Returns 404

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#63]
**Login Button on Signup Page Returns 404**

### Issue Summary

When clicking the Login button on the signup page, a 404 error is triggered. The login page does not seem to be linked correctly from the signup page.

### Steps to Reproduce

1. Go to the signup page.
2. Click the "Login" button.

### Actual Results

A 404 error page is displayed.

### Expected Results

The user should be redirected to the login page.

**Kindly assign this issue to me and add appropriate labels.**

**Comment by MitulSonagara** [comment]
@rashmibarodiya 
You can start working
