### ISSUE TITLE
Feat: Implement Randomly Generated Usernames for Google Sign-In

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#65]
Currently, when users sign in using their Google account, their username is generated from their email address.

![gmail](https://github.com/user-attachments/assets/ac5aae5e-d7ee-4c21-9925-efbed8acf9ba)

 This practice is not ideal for user privacy and experience. 

### Planned Improvements:

Generate a random username for users upon Google sign-in instead of username extracting from their email address.

Please assign this issue to me and apply the appropriate labels.

**Comment by MitulSonagara** [comment]
@rashmibarodiya 

You can start working
