### ISSUE TITLE
[BUG]Issue: Disruption in Sign-In Functionality with Credentials

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#68]
**Description:**
The sign-in functionality with credentials has been disrupted inadvertently during development. As a result, users are currently unable to log in using their account credentials.

**To Reproduce:**

1. Go to /sign-in
2. Fill in the credentials
3. Click Sign In

**Planned Fix:**
I know how to fix it. Kindly let me do it.

**Comment by MitulSonagara** [comment]
@rashmibarodiya You can start working
