### ISSUE TITLE
[FEATURE] Landing, Dashboard and Profile Page redesign

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#69]
**Is your feature request related to a problem? Please describe.**
There should be clear understanding to users that are using platform.

**Describe the solution you'd like**
- Design a nice landing page
- Improve dashboard
- Improve Profile page

**Describe alternatives you've considered**

**Additional context**

**Comment by PriyanshuPz** [comment]
@MitulSonagara May I work on this issue

**Comment by PriyanshuPz** [comment]
@MitulSonagara, I have designed 
- Landing Page
![image](https://github.com/user-attachments/assets/d66de39b-c089-40d7-9ec1-5390f2418ad8)
![image](https://github.com/user-attachments/assets/ca983fba-5bdb-4421-aa96-bb9b3679173e)


- Dashboard Page
![image](https://github.com/user-attachments/assets/5c782342-3c89-4a1e-a3fd-7053daa22ee0)

- Profile Page
![image](https://github.com/user-attachments/assets/696f7676-ab56-4f1c-bcd4-676110068ecc)

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev you can raise a PR for this...
