### ISSUE TITLE
Issue Templates for this project

### ISSUE THREAD

**Issue by MitulSonagara** [MitulSonagara/truth-tunnel#7]
Anyone who can make better issue Template for this project can comment on this.

**Comment by harish08102004** [comment]
Hey @MitulSonagara I can work on this.

**Comment by MitulSonagara** [comment]
@harish08102004 Go for it.

**Comment by harish08102004** [comment]
Hey @MitulSonagara I have raised the PR, please check it and merge.

**Comment by harish08102004** [comment]
Additionally can you add gssoc-extd label for the same.

**Comment by harish08102004** [comment]
Hey @MitulSonagara I request you to add these labels.
hacktoberfest-accepted
level
