### ISSUE TITLE
[FEATURE] Settings to change username of the user

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#71]
**Is your feature request related to a problem? Please describe.**
User should be able to change their username. as username on Google Auth is not decided by user. it is fetched from email

**Describe the solution you'd like**
A form to submit username

**Describe alternatives you've considered**

**Additional context**

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev Go for it
