### ISSUE TITLE
Login page problem

### ISSUE THREAD

**Issue by Shirisha-16** [MitulSonagara/truth-tunnel#76]
When a user wants to login without registering, it should show that the email has not registered 
![Screenshot 2024-10-13 133938](https://github.com/user-attachments/assets/ebb43c50-9a85-4dcc-a5de-7752827f0b00)
I want to work on this issue 
@MitulSonagara assign me this work with the labels gssoc-ext, hacktoberfest-accepted and level according to issue

**Comment by MitulSonagara** [comment]
@Shirisha-16 

You can start working
