### ISSUE TITLE
Typo in authentication screen: "Sign Ip" should be "Sign In"

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#8]
There’s a small typo on the authentication screen where **"Sign Ip" is displayed instead of "Sign In"**.  This happens when the user is prompted to log in.

Expected Behavior:
The text should say "Sign In to start your anonymous adventure."

**Please assign this issue to me, and I would be happy to work on fixing it.**

Screenshot: 
![Screenshot_20241002_095103](https://github.com/user-attachments/assets/de2175cf-1fe2-44df-84f5-72353d065175)

**Comment by MitulSonagara** [comment]
@rashmibarodiya go for it.
