### ISSUE TITLE
[FEATURE]Contact Us Section

### ISSUE THREAD

**Issue by Bhum-ika** [MitulSonagara/truth-tunnel#86]
**Is your feature request related to a problem? Please describe.**
There is no option for users to contact with.

**Describe the solution you'd like**
I would like to create a form for the same aligning with the theme and will use email.js for its functionality

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by MitulSonagara** [comment]
@Bhum-ika 

You can start working

**Comment by Bhum-ika** [comment]
okay

**Comment by Bhum-ika** [comment]
@MitulSonagara is this issue really completed?? 
I was working on it

**Comment by MitulSonagara** [comment]
@Bhum-ika 

after taking too much time by you... this issue is completed. Now there is a contact us page but backend is not connected with it and also some UI improvement is needed... So if you want to work then you can raise new issue.... And please make sure you will raise PR within 2 days

**Comment by Bhum-ika** [comment]
I am sorry for the delay, I will do it soon this time
