### ISSUE TITLE
[FEATURE]Including Images on Home page

### ISSUE THREAD

**Issue by Bhum-ika** [MitulSonagara/truth-tunnel#87]
**Is your feature request related to a problem? Please describe.**
At a glance, we should be getting the meaning of website, which is not happening in this case

**Describe the solution you'd like**
Some elements like images should be used to convey the purpose of this website

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by MitulSonagara** [comment]
@Bhum-ika 

you can start working

**Comment by Bhum-ika** [comment]
sure
