### ISSUE TITLE
[UI]Redesign Sign-Up and Sign-In Pages to Fix Overflow and Improve Layout 

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#88]
**Description**

 **Redesign Sign-Up and Sign-In Pages** to Fix Overflow and Improve Layout (**Potentially including navbar** at the top for easier navigation, if it fits the design)

**Current Behavior**
The current layout of both the sign-up and sign-in pages overflows beyond the visible screen, resulting in a poor user experience.

**Screenshots**
![Screenshot 2024-10-14 094240](https://github.com/user-attachments/assets/317f4b79-9957-4e06-a7a8-0fee5d3c4f3f)

![Screenshot 2024-10-14 094315](https://github.com/user-attachments/assets/44a0c6f9-294d-4985-a0e8-e8c134fe315d)

**Proposed Changes:**

1. Fix the layout so the sign-up and sign-in pages fit properly within the visible screen without overflow.
2. Ensure the pages are responsive across various screen sizes .
3. Improve the visual design for consistency and a modern appearance.
4. **Potentially include a navbar at the top for easier navigation, if it fits the design.**

**Impact**
This change will improve usability by ensuring that all elements of the sign-up and sign-in pages are visible on any screen size, eliminating the need for horizontal scrolling. It will also enhance accessibility and visual appeal, making the design more user-friendly and consistent with the overall theme of the system.

**Kindly assign this issue to me and add the appropriate labels.**

**Comment by MitulSonagara** [comment]
@rashmibarodiya 

Go for it
