### ISSUE TITLE
[FEATURE]: Adding Animated Footer to the Website 

### ISSUE THREAD

**Issue by GyanaPrakashSahoo7853** [MitulSonagara/truth-tunnel#89]
**Description**
The current website lacks footer part and social media icons to reach out to the particular admin of the website. Changing the footer into better looking and responsive features.

**Describe the solution you'd like**
> Footer Component: Move the text "Made with ❤️ by Mitul Sonagara © 2024" from the current location to a dedicated footer component.
>Adding social media icons ( Linkedin, Github, Instagram,......) with animation effect when someone hover on it . 
>The footer part helps user to reach out the website admin if user finds any problem or bug in the website.

**Screenshots**
![Screenshot 2024-10-14 114410](https://github.com/user-attachments/assets/1440f997-eca2-47ae-ad1b-8448bcffe2f9)

**Comment by GyanaPrakashSahoo7853** [comment]
I would like to work on it 
@MitulSonagara Please assign me this issue hacktoberfest and gssoc-extd

**Comment by Sonuu20** [comment]
@GyanaPrakashSahoo7853 seems interesting, I'd also work on this issue

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

I am assigning this to you

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853
> 
> I am assigning this to you

I am not getting the HTML and CSS file of the website. Can i simply add the footer part html  and css files in the folder .vscode ?

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

yes you can use html and css but make sure not to break code consistency...
And you can add css in public folder make new folder for css

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853 
> 
> yes you can use html and css but make sure not to break code consistency...
> And you can add css in public folder make new folder for css

Bhaiya can we please discuss some issues related to the commits and github in discord tomorrow at 12 pm

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

Sorry bro at day time i am not available... we can connect in 9 to 11pm

**Comment by GyanaPrakashSahoo7853** [comment]
> @GyanaPrakashSahoo7853 
> 
> Sorry bro at day time i am not available... we can connect in 9 to 11pm

Can we connect at 9:45 pm

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

Sure bro

**Comment by GyanaPrakashSahoo7853** [comment]
Can we connect now

**Comment by MitulSonagara** [comment]
@GyanaPrakashSahoo7853 

ya we can connect now

sry i was little busy when you messaged

**Comment by GyanaPrakashSahoo7853** [comment]
I am waiting at discord Alumni VC
