### ISSUE TITLE
Feature Request: Add Google provider support (and potential for other providers) in NextAuth

### ISSUE THREAD

**Issue by rashmibarodiya** [MitulSonagara/truth-tunnel#9]
Description:
The application currently uses NextAuth for username, password, and email-based authentication. **Adding a Google login option** would enhance the user experience by allowing users to log in using their Google accounts. Other social login providers can be considered if required.

Proposed Solution:
 
 Integrate the Google provider into the NextAuth configuration.

Benefits:

1. Makes the login process easier and more flexible.
2. Gives users a popular social login option.

Screenshot:
![Screenshot_20241002_095103](https://github.com/user-attachments/assets/d5d365f6-cc4d-40b9-a370-f60d64124013)

**Please assign this issue to me, and I would be happy to work on adding these features.**

**Comment by MitulSonagara** [comment]
@rashmibarodiya Go for it.

But be careful about folder structure and flow of the project.

**Comment by Sourabh782** [comment]
Hii @MitulSonagara is this issue available?

**Comment by MitulSonagara** [comment]
@Sourabh782 

Sorry brother @rashmibarodiya is working on this issue... But she is having some probleme when i deploy the pull request.. You can see the PR... If you want you can help her I will assign it to both

**Comment by Sourabh782** [comment]
> @Sourabh782
> 
> Sorry brother @rashmibarodiya is working on this issue... But she is having some probleme when i deploy the pull request.. You can see the PR... If you want you can help her I will assign it to both

ohh no worries :))
