### ISSUE TITLE
[FEATURE] Add a Toaster Message to notify users

### ISSUE THREAD

**Issue by Akshithsaai** [MitulSonagara/truth-tunnel#90]
**Is your feature request related to a problem? Please describe.**
While Login using same wrong credentials, User should get notified about the error. ( Please Signup , User doesnot exist) or Invalid Credentials . 

**Describe the solution you'd like**
I want to add a toaster to notify the users regarding this issue.

**Additional context**
@MitulSonagara I would like to work on this issue .

![image](https://github.com/user-attachments/assets/46ad5f83-4ae1-4037-9460-dc414db9853b)

**Comment by MitulSonagara** [comment]
@Akshithsaai 

You can start working
