### ISSUE TITLE
[FEATURE] Change encryption key option

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#92]
**Is your feature request related to a problem? Please describe.**
Their is currently no option to change encryption key when expired.
Add a feature to do that.

**Describe the solution you'd like**
- make a new modal for that
- verify password and check encryption key
- update that in local storage
- when user log in on new device then prompt to set private key again

**Describe alternatives you've considered**

**Additional context**

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

go for it
