### ISSUE TITLE
[FEATURE] Forget Encryption key option 

### ISSUE THREAD

**Issue by PriyanshuPz** [MitulSonagara/truth-tunnel#93]
**Is your feature request related to a problem? Please describe.**
If user forget or lost Encryption key then feature to generate new one.

**Describe the solution you'd like**
- Verify identity by asking password
- deleting old encryption key
- generating new encryption key and deleting old messages encrypted with old key.

**Describe alternatives you've considered**

**Additional context**

**Comment by MitulSonagara** [comment]
@priyanshuverma-dev 

Go for it
