### ISSUE TITLE
[FEATURE] Strong Password validation (Important)

### ISSUE THREAD

**Issue by aryadevesh** [MitulSonagara/truth-tunnel#99]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when I try to put very easy password and my account security is compromised. Many times google also throw a pop saying you have a leaked password.

**Describe the solution you'd like**
I would like to implement strong password checker in the signup page which will allow the user to enter only strong(standard) password.

**Describe alternatives you've considered**
There is one alternative which is that, we can put one button for generating strong password automatically.

**Additional context**
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/83db63ea-0e97-45ab-ac95-668cab64d430">

**Comment by MitulSonagara** [comment]
@aryadevesh go for it

**Comment by MitulSonagara** [comment]
@aryadevesh 

I am closing this issue as there are no updates till assigning

**Comment by aryadevesh** [comment]
I had resolved 3 issues in this repo today only, due to very tight schedule I am able to give less time. If you can open this again then I will complete this by tomorrow for sure.

**Comment by MitulSonagara** [comment]
@aryadevesh 

you can work on this
